export enum Type {
	AND = 'and',
	OR = 'or',
	DOUBLE_QUOTES = '"',
	SINGLE_QUOTES = "'",
	LEFT_PAREN = '(',
	RIGHT_PAREN = ')',
	LEFT_BRACE = '{',
	RIGHT_BRACE = '}',
	COMMA = ',',
	DOT = '.',
	MINUS = '-',
	PLUS = '+',
	SEMICOLON = ';',
	STAR = '*',
	BANG_EQUAL = '!=',
	BANG = '!',
	EQUAL = '=',
	EQUAL_EQUAL = '==',
	LESS_EQUAL = '<=',
	LESS = '<',
	GREATER_EQUAL = '>=',
	GREATER = '>',
	VAR = 'var',
	SLASH = '/',
	WHITE_SPACE = ' ',
	CARRIAGE = '\r',
	LINE_FEED = '\n',
	TAB = '\t',
	FUNCTION = 'fn',
	RETURN = 'return',
	ELSE = 'else',
	IF = 'if',
	ELSE_IF = 'else if',
	THIS = 'this',
	WHILE = 'while',
	FOR = 'for',
	NIL = 'nil',
	CLASS = 'class',
	TRUE = 'true',
	FALSE = 'false',
	PRINT = 'print',
	SUPER = 'super'
}
